// Generated from content/site.json by tools/build.py.
window.SITE_CONFIG = {
  "weddingDateTime": "2027-01-23T12:30:00+00:00",
  "theme": {
    "colors": {
      "ink": "#3D3026",
      "paper": "#F4EBDD",
      "paperAlt": "#E9DBC7",
      "accent": "#78563B",
      "accent2": "#91683E"
    },
    "fontPair": "Playfair Display|Work Sans"
  },
  "sections": {
    "hero": true,
    "details": true,
    "gifts": true,
    "story": true,
    "faq": true,
    "contact": true
  },
  "content": {
    "hero.venue": "Igreja de Nossa Senhora das Mercês, Lisboa",
    "honeymoon.title": "Lua de Mel na Patagónia",
    "honeymoon.intro": "Queremos começar esta grande aventura juntos num dos lugares mais bonitos do planeta - na Patagónia Argentina e Chilena.",
    "honeymoon.chalten": "El Chaltén · Fitz Roy",
    "honeymoon.paine": "Torres del Paine",
    "nav.monogram": "Kika e Miguel",
    "countdown.days": "dias",
    "countdown.hours": "horas",
    "countdown.minutes": "min.",
    "countdown.seconds": "seg.",
    "nav.story": "A nossa história",
    "nav.gifts": "Presentes",
    "nav.details": "Onde",
    "nav.faq": "FAQ",
    "details.title": "Onde",
    "details.dressCode": "Dress Code: Fraque",
    "details.intro": "Conhecemo-nos em Lisboa, vamos viver em Lisboa e casamos também em Lisboa!",
    "gifts.title": "Presentes",
    "gifts.intro": "A vossa presença é o mais importante, mas se nos quiserem ajudar a começar esta nossa nova fase, deixamos algumas ideias de presentes.",
    "house.title": "A Nossa Nova Casa",
    "house.intro": "Quem casa quer casa! Queremos montar uma casa acolhedora para a nossa família e sempre pronta para vos receber a todos!",
    "house.caption.bimby": "Bimby TM7",
    "house.caption.bed": "Cama Marriott",
    "house.caption.sofa": "Sofá",
    "house.photo.bimby": "Bimby TM7 para a nossa nova casa",
    "house.photo.bed": "Cama Marriott para a nossa nova casa",
    "house.photo.sofa": "Sofá bege de três lugares para a nossa nova casa",
    "bank.iban": "PT50 0018 000370175294020 34",
    "bank.bic": "TOTAPTPL",
    "bank.mbWayMiguel": "916202487",
    "bank.mbWayKika": "931847410",
    "bank.copy": "Copiar IBAN",
    "bank.copied": "IBAN copiado",
    "bank.copySuccess": "IBAN copiado.",
    "bank.copyError": "Não foi possível copiar automaticamente. O IBAN está selecionado para copiar manualmente.",
    "story.title": "A Nossa História",
    "story.workNumber": "01",
    "story.work": "O Início",
    "story.workDescription": "Conhecemo-nos a trabalhar juntos na McKinsey.",
    "story.caption.work": "McKinsey, às 01:24",
    "story.photo.work": "Kika e Miguel na McKinsey (fotografia tirada às 01:24!)",
    "story.caption.firstDate": "O nosso primeiro \"date\" a ver o pôr-do-sol no guincho",
    "story.photo.firstDate": "O nosso primeiro \"date\" a ver o pôr-do-sol no guincho",
    "story.funNumber": "02",
    "story.fun": "A Divertirmo-nos",
    "story.funDescription": "Quando demos por isso, já andávamos a inventar cada vez mais coisas para fazer juntos.",
    "story.caption.douro": "Pelo Douro",
    "story.photo.douro": "Kika e Miguel no Douro",
    "story.caption.karts": "Kika nos karts",
    "story.photo.karts": "Apesar de não guiar no dia-a-dia, a Kika é TOP RACER nos Karts",
    "story.caption.bankers": "A representar os bancários",
    "story.photo.bankers": "A representar a classe dos Bancários!",
    "story.caption.hike": "Pela Serra da Estrela",
    "story.photo.hike": "Caminhada na Serra da Estrela",
    "story.proposalNumber": "03",
    "story.proposal": "O Pedido",
    "story.proposalDescription": "Fomos a Paris para ir à Disney, mas o Miguel tinha outros planos...",
    "story.caption.proposal": "O nosso primeiro jantar em Paris",
    "story.photo.proposal": "O pedido foi feito no nosso primeiro jantar em Paris!",
    "story.caption.proposalMemories": "Closerie des Lilas",
    "story.photo.proposalMemories": "O Jantar foi na 'closerie de lilas' - a 'casa' do Hemingway e Cole Porter, entre outros!",
    "story.caption.disneyland": "O dia seguinte, na Disneyland",
    "story.photo.disneyland": "O dia seguinte foi passado na Disneyland!",
    "story.caption.paris": "A passear por Paris",
    "story.photo.paris": "E o último dia foi passado a passear por Paris.",
    "faq.title": "FAQ",
    "faq.dressCode": "Fraque.",
    "faq.rentalIntro": "Sugestões para aluguer:",
    "faq.rentalAltaRoda": "Alta Roda",
    "faq.rentalDiadema": "Diadema",
    "parking.church": "Parque Largo de Jesus Telpark — mesmo ao lado da Igreja das Mercês. Aberto 24 horas/dia. Primeira hora 2 €",
    "parking.estufaIntro": "Pode estacionar na rua, na Alameda Edgar Cardoso, ou no ",
    "parking.saba": "parque Saba Alto do Parque",
    "parking.uber": ". Se vier de Uber, pode ir até à porta da Estufa Fria.",
    "faq.venueDirections": "Siga o percurso assinalado a verde na planta, desde a entrada da Estufa Fria até à Nave, onde será o Almoço",
    "faq.mapHint": "Selecione a planta para ampliar.",
    "faq.question.children": "É para levar crianças?",
    "faq.answer.children": "Não estamos a contar com crianças para o Almoço, mas temos todo o gosto se quiserem trazer os vossos filhos para a missa para nos verem casar!",
    "faq.question.hotels": "Têm alguma recomendação de hotéis?",
    "faq.answer.hotels": "Em Lisboa é tudo perto, mas duas opções ao pé do sítio da festa são",
    "faq.hotel.sanaRex": "SANA Rex Hotel",
    "faq.hotel.smyLisboa": "Smy Lisboa",
    "contact.title": "Contacto",
    "contact.email": "kikaemiguel2027@gmail.com",
    "contact.phoneMiguel": "REMOVED",
    "contact.phoneKika": "REMOVED",
    "footer.monogram": "Kika e Miguel",
    "closing.videoCaption": "We can't wait to see you there!!!",
    "closing.videoFallback": "Ver vídeo",
    "closing.videoPlay": "Reproduzir vídeo",
    "closing.videoPause": "Pausar vídeo",
    "faq.question.1": "Qual é o dress code?",
    "faq.question.2": "Onde posso estacionar perto da Igreja das Mercês?",
    "faq.question.3": "Onde posso estacionar perto da Estufa Fria?",
    "faq.question.4": "Como chego ao sítio do Almoço dentro da estufa fria?",
    "couple.name": "Kika e Miguel",
    "event.ceremony": "Missa",
    "event.reception": "Almoço e Festa"
  }
};
