// Generated from content/site.json by tools/build.py.
window.SITE_CONFIG = {
  "weddingDateTime": "2027-01-23T12:30:00+00:00",
  "theme": {
    "colors": {
      "ink": "#3D3026",
      "paper": "#F4EBDD",
      "paperAlt": "#E9DBC7",
      "accent": "#78563B",
      "accent2": "#91683E"
    },
    "fontPair": "Bodoni MT Bold|Work Sans"
  },
  "sections": {
    "hero": true,
    "details": true,
    "gifts": true,
    "story": true,
    "faq": true,
    "contact": true
  },
  "content": {
    "hero.venue": "Igreja de Nossa Senhora das Mercês, Lisboa",
    "honeymoon.title": "Lua de mel na Patagónia",
    "honeymoon.intro": "Entre as montanhas de El Chaltén e as paisagens de Torres del Paine, vamos celebrar o início desta nova aventura juntos.",
    "honeymoon.chalten": "El Chaltén · Fitz Roy",
    "honeymoon.paine": "Torres del Paine",
    "nav.monogram": "Kika e Miguel",
    "countdown.days": "dias",
    "countdown.hours": "horas",
    "countdown.minutes": "min.",
    "countdown.seconds": "seg.",
    "nav.story": "A nossa história",
    "nav.gifts": "Presentes",
    "nav.details": "Onde",
    "nav.faq": "FAQ",
    "details.title": "Onde",
    "details.dressCode": "Dress Code: Fraque",
    "details.intro": "Conhecemo-nos em Lisboa, e queremos continuar aqui a nossa vida. Por isso, escolhemos casar também em Lisboa, na Igreja das Mercês, seguido de um almoço na Estufa Fria.",
    "gifts.title": "Presentes",
    "gifts.intro": "A vossa presença é o mais importante, mas se nos quiserem ajudar nesta nossa nova fase, gostávamos muito de uma contribuição para a nova casa ou para a lua de mel na Patagónia.",
    "honeymoon.fundLabel": "Fundo de lua de mel",
    "bank.iban": "PT50 0018 000370175294020 34",
    "bank.bic": "TOTAPTPL",
    "bank.mbWayMiguel": "916202487",
    "bank.mbWayKika": "931847410",
    "bank.copy": "Copiar IBAN",
    "bank.copied": "IBAN copiado",
    "bank.copySuccess": "IBAN copiado.",
    "bank.copyError": "Não foi possível copiar automaticamente. O IBAN está selecionado para copiar manualmente.",
    "story.title": "A Nossa História",
    "story.workNumber": "01",
    "story.workDescription": "Conhecemo-nos a trabalhar juntos na McKinsey.",
    "story.funNumber": "02",
    "story.funDescription": "Aos poucos fomos ficando mais próximos e começámos a partilhar cada vez mais momentos um do outro.",
    "story.proposalNumber": "03",
    "story.proposalDescription": "O pedido de casamento aconteceu em Paris!",
    "story.photo.work": "Kika e Miguel na McKinsey (fotografia tirada às 01:24!)",
    "story.photo.douro": "Kika e Miguel no Douro",
    "story.photo.karts": "Apesar de não guiar no dia-a-dia, a Kika é TOP RACER nos Karts",
    "story.photo.bankers": "A representar a classe dos Bancários!",
    "story.photo.hike": "Caminhada na Serra da Estrela",
    "story.photo.proposal": "O pedido foi feito no nosso primeiro jantar em Paris!",
    "story.photo.proposalMemories": "O Jantar foi na 'closerie de lilas' - a 'casa' do Hemingway e Cole Porter, entre outros!",
    "story.photo.disneyland": "O dia seguinte foi passado na Disneyland!",
    "story.photo.paris": "E o último dia foi passado a passear por Paris.",
    "faq.title": "FAQ",
    "faq.dressCode": "Fraque.",
    "faq.rentalIntro": "Sugestões para aluguer:",
    "faq.rentalAltaRoda": "Alta Roda",
    "faq.rentalDiadema": "Diadema",
    "parking.church": "Parque Largo de Jesus Telpark — mesmo ao lado da Igreja das Mercês. Aberto 24 horas/dia. Primeira hora 2 €",
    "parking.estufaIntro": "Pode estacionar na rua, na Alameda Edgar Cardoso, ou no ",
    "parking.saba": "parque Saba Alto do Parque",
    "parking.uber": ". Se vier de Uber, pode ir até à porta da Estufa Fria.",
    "faq.venueDirections": "Siga o percurso assinalado a verde na planta, desde a entrada da Estufa Fria até à Nave, onde será a receção.",
    "faq.mapHint": "Selecione a planta para ampliar.",
    "contact.title": "Contacto",
    "contact.email": "kikaemiguel2027@gmail.com",
    "footer.monogram": "Kika e Miguel",
    "faq.question.1": "Qual é o dress code?",
    "faq.question.2": "Onde posso estacionar perto da Igreja das Mercês?",
    "faq.question.3": "Onde posso estacionar perto da Estufa Fria?",
    "faq.question.4": "Como chego ao sítio do Almoço dentro da estufa fria?",
    "couple.name": "Kika e Miguel",
    "event.ceremony": "Missa",
    "event.reception": "Almoço e Festa",
    "story.work": "McKinsey",
    "story.fun": "A Divertirmo-nos",
    "story.proposal": "O Pedido"
  }
};
